title: Wayne's page
author: Wayne
email: WayneWhitley@McHargue.org
theme: jekyll-theme-architect

description: > # this means to ignore newlines until "baseurl:"
   This contains various code snippet descriptions and write-ups
   tracking my development progress.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML"> </script>
