title: Wayne's page
author: Wayne
email: WayneWhitley@McHargue.org
theme: jekyll-theme-tactile

description: > # this means to ignore newlines until "baseurl:"
   This contains various code snippet descriptions and write-ups
   tracking my development progress.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
